/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageBatchIdRouteImport } from './routes/manage.$batchId'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageBatchIdRoute = ManageBatchIdRouteImport.update({
  id: '/manage/$batchId',
  path: '/manage/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage/$batchId': typeof ManageBatchIdRoute
  '/verify/$code': typeof VerifyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage/$batchId': typeof ManageBatchIdRoute
  '/verify/$code': typeof VerifyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage/$batchId': typeof ManageBatchIdRoute
  '/verify/$code': typeof VerifyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manage/$batchId' | '/verify/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manage/$batchId' | '/verify/$code'
  id: '__root__' | '/' | '/manage/$batchId' | '/verify/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageBatchIdRoute: typeof ManageBatchIdRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$batchId': {
      id: '/manage/$batchId'
      path: '/manage/$batchId'
      fullPath: '/manage/$batchId'
      preLoaderRoute: typeof ManageBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageBatchIdRoute: ManageBatchIdRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
